service: createaccount

frameworkVersion: '2'

plugins:
  - serverless-iam-roles-per-function

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  region: us-east-1
  stage: dev

functions:
  - ${file(src/createClient/createClient.yml)}
  - ${file(src/createCard/createCard.yml)}

resources:
  # dynamoDB
  - ${file(resource/dynamo/clients.yml)}
  - ${file(resource/dynamo/cards.yml)}

  # sqs
  - ${file(resource/sqs/createCard.yml)}
