Resources:
  ClientCreatedTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: ${self:service}-${self:provider.stage}-clientCreatedTopic
  ClientCreatedCardSubscription:
    Type: 'AWS::SNS::Subscription'
    Properties:
      TopicArn: !Ref ClientCreatedTopic
      Endpoint: !GetAtt CreateCardQueue.Arn
      Protocol: 'sqs'
      RawMessageDelivery: 'true'
  ClientCreatedGiftSubscription:
    Type: 'AWS::SNS::Subscription'
    Properties:
      TopicArn: !Ref ClientCreatedTopic
      Endpoint: !GetAtt CreateGiftQueue.Arn
      Protocol: 'sqs'
      RawMessageDelivery: 'true'
