Resources:
  CreateGiftQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: createGiftQueue
  CreateGiftQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties: 
      PolicyDocument: 
        Statement:
          Effect: Allow
          Principal: '*'
          Action: 
            - SQS:*
          Resource: !GetAtt CreateGiftQueue.Arn
      Queues: 
        - !Ref CreateGiftQueue
