Resources:
  CreateCardQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: createCardQueue
  CreateCardQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties: 
      PolicyDocument: 
        Statement:
          Effect: Allow
          Principal: '*'
          Action: 
            - SQS:*
          Resource: !GetAtt CreateCardQueue.Arn
      Queues: 
        - !Ref CreateCardQueue